version: '3.1'

services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    container_name: symfony
    build: ./docker
    volumes:
      - .:/app

  db:
    image: 'mariadb'
    env_file: ./.env
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1